# Supabase 프로젝트 구성 파일

# 프로젝트 정보
project_id = "zudnmkyedvhdgftbwatt"

# API 설정
[api]
enabled = true
port = 54321

# 데이터베이스 설정
[db]
port = 54322

# Studio 설정
[studio]
enabled = true
port = 54323

# Edge Functions 설정
[functions]
# subscription-manager-no-auth 함수는 JWT 검증을 비활성화
[functions.subscription-manager-no-auth]
verify_jwt = false

# 기타 함수들은 JWT 검증 활성화 (기본값)
[functions.subscription-manager]
verify_jwt = true

[functions.verify-googleplaypay]
verify_jwt = true

[functions.verify-purchase]
verify_jwt = true

# 인증 설정
[auth]
enabled = true
site_url = "https://zudnmkyedvhdgftbwatt.supabase.co"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = true

# 스토리지 설정
[storage]
enabled = true
file_size_limit = "50MB"